### ISSUE TITLE
[Register] Empty date fields are using the date of the registration as default

### ISSUE THREAD

**Issue by artandor** [artandor/diabetehelper#5]
Current 👎 
Empty date fields are using the date of the registration as default wich means profiles have fake datas.

Expected 👍
If the user doesn't want to provide those datas, we should just register the field as null.

**Comment by vasilvestre** [comment]
For exemple 
`  /**
   * @var \DateTime
   *
   * @ORM\Column(name="dateInscription", type="datetime", nullable=true)
   */
  private $dateInscription;`

Should be

`  /**
   * @var \DateTime
   *
   * @ORM\Column(name="dateInscription", type="datetime", nullable=true)
   */
  private $dateInscription = null;`

**Comment by vasilvestre** [comment]
There's also this but I'm not sure. 

`@Orm\Column(name="dateInscription", type="datetime", nullable=true, default=null)`

Should be not required in form if optionnable

`->add('dueDate', DateType::class, array(
    'widget' => 'single_text',
    'required' => false
))`

**Comment by artandor** [comment]
The bug was an error i made in the template, not in the form.
Problem solved by adding `    {% if user.yearofbirth is not null %}{%endif%}` around the age.

@vasilvestre 
`@Orm\Column(name="dateInscription", type="datetime", nullable=true, default=null)`
doesn't work, default is not a valid property of @ORM\Column

**Comment by vasilvestre** [comment]
So just define the value

`private $dateInscription = null;`
