### ISSUE TITLE
[register] /!\ Major !!  Register not working

### ISSUE THREAD

**Issue by artandor** [artandor/diabetehelper#9]
Register doesn't work when weight and size are filled
Values tested : 70 weight 174 height

Profiler link : [Profiler](http://nmylle.eu/app_dev.php/_profiler/dcc08e?panel=swiftmailer)

> Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, weight, height, year_of_birth, bloodType, lastHb1c, lastHb1cDate, typeDiabete, typeTraitement, insulinSensivity, glycemicObjective, dateInscription) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["ert", "ert", "eret@ert.fr", "eret@ert.fr", 0, null, "$2y$13$3VVTmA3gmpeQGKirumKtkOAQXtRPlb6wBKp.OzG6MeokEiyhk3jiK", null, "f3HZsRKH6mvTmLY6GY6vNXjB8Qh2asgfSEtp9SO-yZI", null, "a:0:{}", 70, 174, null, null, null, "2012-01-01 00:00:00", 2, null, 4, 4, null]: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'height' at row 1" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115

**Comment by vasilvestre** [comment]
`  /**
   * @param float $weight
   */
  public function setWeight($weight) {
    $this->weight = $weight;
  }` in [https://github.com/artandor/diabetehelper/blob/master/src/DiabeteHelperBundle/Entity/User.php](url)

I think it wait for float value, like 12,00, the form type is like
`->add(
        'weight',
        NumberType::class,
        array(
          'label' => 'Your weight',
          'required' => FALSE,
        )
      )` in [https://github.com/artandor/diabetehelper/blob/master/src/DiabeteHelperBundle/Form/Type/RegistrationType.php](url)

Maybe give a try for a 

- IntegerType:class

- rounded option in Type

- change double to integer
